name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make changes
        run: |
          echo "Some changes" >> last_run.txt

      - name: Commit changes
        run: |
          git config --global user.name "Nelson Jochim DSouza"
          git config --global user.email "22f1001290@ds.study.iitm.ac.in"
          git add .
          git commit -m "Daily update"

      - name: Pull latest changes
        run: git pull --rebase origin main

      - name: Push changes
        run: git push origin main
